name: manjaro-arm-rootfs

on:
  workflow_dispatch:
    inputs:
      desktop:
        description: 'Desktop meta-package'
        required: false
        default: 'xfce4'
        type: choice
        options:
          - minimal
          - xfce4
          - kde
          - gnome
      extra:
        description: 'Space-separated extra packages'
        required: false
        default: 'lightdm lightdm-gtk-greeter ttf-dejavu'
  schedule:
    - cron: '30 3 * * 3'

permissions:
  contents: write

env:
  CACHE_VER: 1    # 手动 bump 以强制失效缓存

jobs:
  rootfs:
    runs-on: ubuntu-22.04
    steps:
      # ---------- 1. 时间戳 ----------
      - id: time
        uses: boredland/get-time-action@v2

      # ---------- 2. 检查输入 ----------
      - name: vars
        id: vars
        run: |
          DESK="${{ github.event.inputs.desktop || 'xfce4' }}"
          EXT="${{ github.event.inputs.extra || 'lightdm lightdm-gtk-greeter ttf-dejavu' }}"
          echo "desk=$DESK" >> $GITHUB_OUTPUT
          echo "extra=$EXT" >> $GITHUB_OUTPUT

      # ---------- 3. 缓存：pacman 缓存 ----------
      - name: cache-pacman
        uses: actions/cache@v4
        with:
          path: ~/pacman-cache
          key: pacman-${{ env.CACHE_VER }}-${{ steps.time.outputs.time }}
          restore-keys: pacman-${{ env.CACHE_VER }}-

      # ---------- 4. 缓存：mirrorlist ----------
      - name: cache-mirrorlist
        uses: actions/cache@v4
        with:
          path: /tmp/mirrorlist
          key: mirror-${{ env.CACHE_VER }}

      # ---------- 5. 安装官方二进制包（零编译） ----------
      - name: install-tools
        run: |
          sudo apt-get update -qq
          sudo apt-get install -yqq \
            qemu-user-static systemd-container zstd \
            wget tar curl
          # 官方 arch-install-scripts 已打 deb
          sudo apt-get install -yqq arch-install-scripts

          # pacman 官方 nightly deb（ARM 支持已合并主线）
          wget -qO- https://pkgbuild.com/~pierrep/public/pacman-latest.deb | sudo dpkg -i -

          # 首次初始化 keyring（缓存加速）
          sudo mkdir -p /etc/pacman.d/gnupg
          sudo pacman-key --init || true

      # ---------- 6. 准备 mirrorlist ----------
      - name: mirrorlist
        run: |
          if [[ ! -f /tmp/mirrorlist ]]; then
            curl -L -o /tmp/mirrorlist \
              https://gitlab.manjaro.org/manjaro-arm/applications/manjaro-arm-tools/-/raw/master/profiles/defaults/arm64/mirrorlist
          fi
          sudo mv /tmp/mirrorlist /etc/pacman.d/mirrorlist

      # ---------- 7. 注册 qemu ----------
      - name: qemu-binfmt
        run: |
          sudo wget -qO /usr/lib/binfmt.d/qemu-aarch64-static.conf \
            https://gitlab.manjaro.org/manjaro-arm/packages/manjaro-arm-qemu-static/-/raw/master/qemu-static.conf
          sudo systemctl restart systemd-binfmt

      # ---------- 8. 生成 rootfs ----------
      - name: pacstrap
        run: |
          ROOTFS=$PWD/rootfs
          sudo rm -rf "$ROOTFS"
          sudo mkdir -p "$ROOTFS"

          # 基础包
          PKG="base sudo systemd nano vim tar xz gzip sed ca-certificates ca-certificates-utils"
          # 桌面
          [[ "${{ steps.vars.outputs.desk }}" != "minimal" ]] && PKG+=" ${{ steps.vars.outputs.desk }} ${{ steps.vars.outputs.extra }}"

          # 使用宿主缓存目录
          sudo pacstrap -c -K "$ROOTFS" $PKG

          # 清理
          sudo rm -f "$ROOTFS"/var/lib/pacman/sync/*.db.sig
          sudo arch-chroot "$ROOTFS" pacman -Scc --noconfirm
          sudo rm -f "$ROOTFS"/etc/machine-id
          sudo touch "$ROOTFS"/etc/machine-id

          # 打包 zstd -19
          sudo tar -C "$ROOTFS" -cf - . | zstd -19 -o manjaro-${{ steps.vars.outputs.desk }}-${{ steps.time.outputs.time }}.tar.zst
          sudo chown $USER:$USER manjaro-*.tar.zst

      # ---------- 9. 上传 Release ----------
      - name: release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.vars.outputs.desk }}-${{ steps.time.outputs.time }}
          name: "Manjaro ARM ${{ steps.vars.outputs.desk }} ${{ steps.time.outputs.time }}"
          files: manjaro-*.tar.zst
